### ISSUE TITLE
Adding a class doesn't override backgroundColor

### ISSUE THREAD

**Issue by CharlieIGG** [apvarun/toastify-js#20]
If I do NOT set a backgroundColor option when calling Toastify, but add a `className` that maps for instance to a Bootstrap alert class, the Toast's default backgroundColor still takes precedence over the class' background color.

i.e.

```javascript
 Toastify({
    text: "A simple warning alert—check it out!",
    duration: 3000,
    close: true,
    gravity: "bottom",
    positionLeft: false,
    className:"alert alert-warning>"
    }).showToast();
```

Should yield the following:

![image](https://user-images.githubusercontent.com/14896457/53855524-9f7ca800-3f93-11e9-9d33-9607d40b16fb.png)

Instead I get:

![image](https://user-images.githubusercontent.com/14896457/53855546-b4f1d200-3f93-11e9-9692-6f2d6d0c7102.png)

**Comment by apvarun** [comment]
Hey @CharlieIGG,
The issue that you are facing is a side-effect of using a gradient background as default. Linear gradient requires to use `background` property where as bootstrap sets the color of alert using `background-color`. Setting a default background was done in order to make **Toastify** a simple drop-in library for anyone to use.

But for the issue of style not being applied, you will need to import the bootstrap css from your JS file for it to take effect.
**Demo:** https://codesandbox.io/s/8kyk48zoll

Let me know your thoughts of this.

**Comment by AlexisTM** [comment]
@apvarun What about adding a class for the default gradient that is the default value of the `className` property?

**Comment by CharlieIGG** [comment]
FYI I ended up doing the following to achieve what I wanted (thankfully I was already packing SCSS):

```scss
@each $color,
$value in $theme-colors {

  .toastify.alert-#{$color},
  .alert-#{$color} {
    @include alert-variant(theme-color-level($color, $alert-bg-level), theme-color-level($color, $alert-border-level), color-yiq(theme-color-level($color, $alert-bg-level)));

    .close,
    .alert-link {
      color: color-yiq(theme-color-level($color, $alert-bg-level));
    }
  }
}
```
