### ISSUE TITLE
More settings, like setup the space between toast

### ISSUE THREAD

**Issue by HectorLS** [apvarun/toastify-js#7]
Hello,
first of all nice library ! 🎉 
Quite clean with nice support.

would be nice to have in the options 🙏 the possibility to setup:
- space between toast ( like margin between each other )
- choose the wrapper className
- Pass html instead of only a string ( i need to create a toast with a tiny thumbnail image for example and its not possible 😢 

And as an improvement 💡 i think its way [better to use transform translate instead of top/bottom to move objects](https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/) by the performance 

Thanks in advance

**Comment by rndevfx** [comment]
For class names: https://github.com/apvarun/toastify-js/pull/5

**Comment by apvarun** [comment]
I think modifying the classes field to an array of class names while invoking would be better than having a string.

Like this:
```js
Toastify({
    text: "This is a toast",
    backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
    classes: ["info", "transparent"]
}).showToast();
```

**Comment by rndevfx** [comment]
Yes, I agree that the naming is a little bit difficult now. But using class names as array is slower, because we have to join them later again. What about using

``
className: "info transparent"
``
This is more generic (like in the toastify code itself) and could works for a single or multiple space separated class names.

**Comment by rndevfx** [comment]
@apvarun Created a new PR with the cleanup

**Comment by rndevfx** [comment]
@HectorLS It's possible to pass markup to your text as string.

Example:
```javascript
Toastify({
  text: "<b>Bold</b> Hi",
  duration: 4500,
  gravity: "top",
  positionLeft: true,
}).showToast();
```

Do you have a special case?

**Comment by HectorLS** [comment]
Sorry by the delay !
Awesome news @rndevfx  , gonna update it !

Seems like there is only my first suggestion remaining. so cool.
by now i just now that the space between toast is 15px so i'm substracting then. but its not the cleanest solution

```scss
$toast-space-between: 15px;

.toastify {
  @for $i from 1 through 30 {
    $element__position: $i + 'n';
    $value: $i * $toast-space-between;
    
    &:nth-child(#{$element__position}) {
      &.on {
        transform: translate(-50%, $value);
      }
    }
  }
}
```

So if you put a value < 15px would be the space, and of course can be negative to increase the default one.
